
=encoding utf8

=cut

$Id$

=head1 NAME

pam_geoip - GeoIP account management module for (Linux-)PAM

=head1 SYNOPSIS

 account required pam_geoip.so [system_file=file] [geoip_db=file]
        [action=name] [language=name] [debug]

=head1 DESCRIPTION

The B<pam_geoip> module provides a check if the remote logged in user is
logged in from a given location. This is similar to L<pam_access(8)>, but
uses a GeoIP2 City or GeoIP2 Country database instead of
host name / IP matching.

The matching is done on given country and city names or on distance from
a given location. With a country database only matches of the countries are
possible.

This PAM module provides the I<account> hook only.

If an IP is not found in the GeoIP2 database, the location to match against
is set to C<UNKNOWN, *>, no distance matching is possible for these,
of course.

If a file named F</etc/security/geoip.SERVICE.conf> (with SERVICE being the
name of the PAM service) can be opened, this is used instead of the default
F</etc/security/geoip.conf>.

The first matching entry in the L<geoip.conf(5)> file wins, i.e. the action
given in this line will be returned to PAM:

=over 4

=item allow

PAM_SUCCESS

=item deny

PAM_PERM_DENIED

=item ignore

PAM_IGNORE

=back

=head1 OPTIONS

These options may be given in the PAM config file as parameters:

=over 4

=item system_file=/path/to/geoip.conf

The configuration file for B<pam_geoip>. Default is
F</etc/security/geoip.conf>. For the format of this file, see L<geoip.conf(5)>.

B<NOTE>: when a file F</etc/security/geoip.SERVICE.conf> file is present, this
switch is ignored (with C<SERVICE> being the name of the PAM service, e.g.
C<sshd>).

=item geoip_db=/path/to/GeoLite2-City.mmdb

The GeoIP2 database to use. Default: F</usr/share/GeoIP/GeoLite2-City.mmdb>.
This must be a C<GeoIP2 City Edition> or a C<GeoIP2 Country Edition> file, see
L<https://www.maxmind.com/en/geoip2-databases> and
L<https://dev.maxmind.com/geoip/geoip2/geolite2/> for more information.

The database can contain IPv4 or IPv6 addresses or both.

=item action=ACTION

Sets the default action if no location matches. Default is C<deny>. Other
possible values are C<allow> or C<ignore>. For the meanigns of these, see
above.

=item language=NAME

Sets the language to be used to find names (city etc.). Default is C<en>.

=item debug

Adds some debugging output to syslog.

=back

=head1 FILES

=over 4

=item /etc/security/geoip.conf

The default configuration file for this module

=item /etc/security/geoip.SERVICE.conf

The default configuration file for PAM service SERVICE

=item /etc/pam.d/*

The L<PAM(7)> configuration files

=back

=head1 SEE ALSO

L<geoip.conf(5)>, L<pam_access(8)>, L<pam.d(5)>, L<pam(7)>

=head1 AUTHOR

Amish - GeoIP2
Hanno Hecker - Legacy GeoIP C<E<lt>vetinari@ankh-morp.orgE<gt>>

=cut
